# Generated by Django 6.1 on 2026-08-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_registration', models.BooleanField(default=True, verbose_name='Permitir registro de nuevos usuarios')),
                ('site_name', models.CharField(default='Nooxial', max_length=100, verbose_name='Nombre del sitio')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Modo mantenimiento')),
            ],
            options={
                'verbose_name': 'Configuración general',
                'verbose_name_plural': 'Configuración general',
            },
        ),
    ]
