# Generated by Django 6.1 on 2026-08-16 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_pin_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='attendance_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de asistencia'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='default_from_email',
            field=models.CharField(blank=True, help_text='Ej: Nooxial <no-reply@tudominio.com>. Si está vacío se usa el usuario SMTP.', max_length=255, verbose_name='Dirección "De" por defecto'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contraseña SMTP'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='email_host_user',
            field=models.CharField(blank=True, max_length=255, verbose_name='Usuario SMTP (email remitente)'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-created_at'],
            },
        ),
    ]
