# Generated by Django 6.1 on 2026-08-16 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_direct_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Términos y Condiciones', max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Contenido')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='Versión')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo (requiere aceptación)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Términos y condiciones',
                'verbose_name_plural': 'Términos y condiciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptances', to=settings.AUTH_USER_MODEL)),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='accounts.termsconditions')),
            ],
            options={
                'verbose_name': 'Aceptación de términos',
                'verbose_name_plural': 'Aceptaciones de términos',
                'ordering': ['-accepted_at'],
                'unique_together': {('user', 'terms')},
            },
        ),
    ]
