# Generated by Django 6.1 on 2026-08-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_terms_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='cookie_consent_enabled',
            field=models.BooleanField(default=True, verbose_name='Mostrar aviso de cookies'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cookie_consent_text',
            field=models.TextField(blank=True, default='Utilizamos cookies propias y de terceros para mejorar tu experiencia, analizar el tráfico y personalizar el contenido de acuerdo con nuestra Política de Privacidad. Al hacer clic en "Aceptar" consientes el uso de todas las cookies. Puedes gestionar tus preferencias en cualquier momento.', verbose_name='Texto del aviso de cookies'),
        ),
    ]
