# Generated by Django 6.1 on 2026-08-16 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_siteconfig_cookie_consent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('companies', models.ManyToManyField(blank=True, related_name='chat_groups', to='accounts.company', verbose_name='Empresas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_groups', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('members', models.ManyToManyField(blank=True, related_name='chat_group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Miembros individuales')),
            ],
            options={
                'verbose_name': 'Grupo de chat',
                'verbose_name_plural': 'Grupos de chat',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChatGroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.chatgroup', verbose_name='Grupo')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Mensaje de grupo',
                'verbose_name_plural': 'Mensajes de grupo',
                'ordering': ['created_at'],
            },
        ),
    ]
