# Generated by Django 6.1 on 2026-08-16 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_chat_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_id', models.CharField(max_length=20, verbose_name='Peer origen')),
                ('target', models.CharField(blank=True, max_length=20, verbose_name='Peer destino')),
                ('stype', models.CharField(max_length=20, verbose_name='Tipo')),
                ('data', models.TextField(blank=True, verbose_name='Datos JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_signals', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Señal WebRTC',
                'verbose_name_plural': 'Señales WebRTC',
                'ordering': ['id'],
            },
        ),
    ]
