# Generated by Django 6.1 on 2026-08-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_meeting_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='curriculos/', verbose_name='Currículum (PDF)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv_public',
            field=models.BooleanField(default=False, verbose_name='Currículum público'),
        ),
    ]
