# Generated by Django 6.1 on 2026-08-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_userprofile_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cv_file',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv_education',
            field=models.TextField(blank=True, verbose_name='Formación académica'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv_experience',
            field=models.TextField(blank=True, verbose_name='Experiencia laboral'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv_headline',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titular profesional'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv_skills',
            field=models.TextField(blank=True, verbose_name='Habilidades y competencias'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv_summary',
            field=models.TextField(blank=True, verbose_name='Resumen profesional'),
        ),
    ]
