# Generated by Django 6.1 on 2026-08-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userprofile_cv_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cv_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono de contacto'),
        ),
    ]
