# Generated by Django 6.1 on 2026-08-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_userprofile_cv_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cv_facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv_instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv_linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv_tiktok',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
    ]
