# Generated by Django 6.1 on 2026-08-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_userprofile_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cv_github',
            field=models.URLField(blank=True, verbose_name='GitHub'),
        ),
    ]
