# Generated by Django 6.1 on 2026-08-17 12:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


def seed_v1(apps, schema_editor):
    AppVersion = apps.get_model('accounts', 'AppVersion')
    AppVersionFeature = apps.get_model('accounts', 'AppVersionFeature')

    v = AppVersion.objects.create(
        version='1.0.0',
        title='Lanzamiento inicial',
        released_at=datetime.date(2026, 8, 17),
        is_current=True,
    )
    features = [
        ('feature',     'Sistema de cursos con lecciones, exámenes y tareas'),
        ('feature',     'Progreso del estudiante y certificados'),
        ('feature',     'Videollamadas y salas de reunión integradas'),
        ('feature',     'Mensajería directa entre usuarios'),
        ('feature',     'Grupos de chat en tiempo real'),
        ('feature',     'Mis Documentos: carpetas, archivos, notas y pizarras'),
        ('feature',     'Presentaciones Markdown con Reveal.js y editor CodeMirror'),
        ('feature',     'Compartir carpetas con usuarios o empresas'),
        ('feature',     'Biblioteca de recursos y artículos'),
        ('feature',     'Plan de capacitación por empresa'),
        ('feature',     'Registro de empresas y gestión de usuarios'),
        ('feature',     'Votaciones y encuestas'),
        ('feature',     'Perfil con CV, foto, redes sociales y GitHub'),
        ('feature',     'Evaluaciones de la plataforma con caritas y comentarios'),
        ('feature',     'Asistencia y tokens de acceso por empresa'),
        ('improvement', 'Diseño responsive con Tailwind CSS (móvil y escritorio)'),
        ('improvement', 'Panel de administración con KPIs y estadísticas'),
        ('improvement', 'Soporte y contactos integrados'),
    ]
    for i, (cat, txt) in enumerate(features):
        AppVersionFeature.objects.create(version=v, category=cat, text=txt, order=i)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_platform_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True, verbose_name='Versión')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('released_at', models.DateField(verbose_name='Fecha de lanzamiento')),
                ('is_current', models.BooleanField(default=False, verbose_name='Versión actual')),
            ],
            options={
                'verbose_name': 'Versión',
                'verbose_name_plural': 'Versiones',
                'ordering': ['-released_at'],
            },
        ),
        migrations.CreateModel(
            name='AppVersionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('feature', '✨ Novedad'), ('improvement', '🔧 Mejora'), ('fix', '🐛 Corrección')], default='feature', max_length=20, verbose_name='Categoría')),
                ('text', models.CharField(max_length=500, verbose_name='Descripción')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='accounts.appversion', verbose_name='Versión')),
            ],
            options={
                'verbose_name': 'Mejora',
                'verbose_name_plural': 'Mejoras',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.RunPython(seed_v1, migrations.RunPython.noop),
    ]
