# Generated by Django 6.1 on 2026-08-15 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_trainingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='training_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.trainingplan', verbose_name='Plan de capacitación'),
        ),
    ]
