# Generated by Django 6.1 on 2026-08-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_categories_course_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images/', verbose_name='Imagen destacada'),
        ),
    ]
