# Generated by Django 6.1 on 2026-08-15 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple', 'Opción múltiple'), ('upload', 'Subir archivo')], default='multiple', max_length=20, verbose_name='Tipo de pregunta'),
        ),
        migrations.CreateModel(
            name='ExamUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='exam_uploads/', verbose_name='Archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='courses.examattempt', verbose_name='Intento')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='courses.question', verbose_name='Pregunta')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
