# Generated by Django 6.1 on 2026-08-16 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_demo_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_teacher_msgs', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_outbox', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_inbox', to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Mensaje a profesor',
                'verbose_name_plural': 'Mensajes a profesores',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], default=5, verbose_name='Valoración')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario público')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_teacher_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Valoración de profesor',
                'verbose_name_plural': 'Valoraciones de profesores',
                'ordering': ['-created_at'],
                'unique_together': {('teacher', 'student')},
            },
        ),
    ]
