# Generated by Django 6.1 on 2026-08-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_user_folder_file_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernote',
            name='share_token',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='Token de compartir'),
        ),
    ]
