# Generated by Django 6.1 on 2026-08-16 12:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_usernote_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='register_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de registro'),
        ),
    ]
