# Generated by Django 6.1 on 2026-08-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_trainingplan_register_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='share_token',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='Token de compartir'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Aperturas'),
        ),
        migrations.AddField(
            model_name='userfolder',
            name='share_token',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='Token de compartir'),
        ),
        migrations.AddField(
            model_name='userfolder',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Aperturas'),
        ),
    ]
