# Generated by Django 6.1 on 2026-08-16 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_userfolder_file_share'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWhiteboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Pizarra sin título', max_length=255, verbose_name='Título')),
                ('data', models.TextField(blank=True, default='', verbose_name='Datos JSON')),
                ('share_token', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Token público')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Aperturas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whiteboards', to='courses.userfolder', verbose_name='Carpeta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_whiteboards', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pizarra',
                'verbose_name_plural': 'Pizarras',
                'ordering': ['-updated_at'],
            },
        ),
    ]
