# Generated by Django 6.1 on 2026-08-17 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_folder_direct_share'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Presentación sin título', max_length=255, verbose_name='Título')),
                ('content', models.TextField(blank=True, verbose_name='Contenido Markdown')),
                ('theme', models.CharField(choices=[('black', 'Negro'), ('white', 'Blanco'), ('league', 'League'), ('beige', 'Beige'), ('sky', 'Cielo'), ('night', 'Noche'), ('serif', 'Serif'), ('simple', 'Simple'), ('solarized', 'Solarized'), ('moon', 'Luna'), ('dracula', 'Dracula')], default='black', max_length=30, verbose_name='Tema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='courses.userfolder', verbose_name='Carpeta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_presentations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
                'ordering': ['-updated_at'],
            },
        ),
    ]
