# Generated by Django 6.1 on 2026-08-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_user_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpresentation',
            name='share_token',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='Token público'),
        ),
        migrations.AddField(
            model_name='userpresentation',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Vistas públicas'),
        ),
    ]
