from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('mis-cursos/', views.my_courses, name='my_courses'),
    path('documentos/', views.biblioteca, name='biblioteca'),
    path('documentos/<int:folder_id>/', views.biblioteca, name='biblioteca_folder'),
    # Mis documentos (personal)
    path('mis-docs/', views.my_docs, name='my_docs'),
    path('mis-docs/carpeta/<int:folder_id>/', views.my_docs, name='my_docs_folder'),
    path('mis-docs/carpeta/nueva/', views.my_docs_new_folder, name='my_docs_new_folder'),
    path('mis-docs/carpeta/<int:folder_id>/nueva/', views.my_docs_new_folder, name='my_docs_new_subfolder'),
    path('mis-docs/carpeta/<int:folder_id>/editar/', views.my_docs_edit_folder, name='my_docs_edit_folder'),
    path('mis-docs/carpeta/<int:folder_id>/eliminar/', views.my_docs_delete_folder, name='my_docs_delete_folder'),
    path('mis-docs/carpeta/<int:folder_id>/subir/', views.my_docs_upload_file, name='my_docs_upload_file'),
    path('mis-docs/archivo/<int:file_id>/eliminar/', views.my_docs_delete_file, name='my_docs_delete_file'),
    path('mis-docs/carpeta/<int:folder_id>/nota/nueva/', views.my_docs_note_edit, name='my_docs_note_new'),
    path('mis-docs/nota/<int:note_id>/editar/', views.my_docs_note_edit, name='my_docs_note_edit'),
    path('mis-docs/nota/<int:note_id>/eliminar/', views.my_docs_note_delete, name='my_docs_note_delete'),
    path('mis-docs/nota/<int:note_id>/compartir/', views.my_docs_note_share, name='my_docs_note_share'),
    path('mis-docs/grabar/', views.my_docs_record_upload, name='my_docs_record_upload'),
    path('mis-docs/archivo/<int:file_id>/compartir/', views.my_docs_share_file,   name='my_docs_share_file'),
    path('mis-docs/carpeta/<int:folder_id>/compartir/', views.my_docs_share_folder, name='my_docs_share_folder'),
    path('mis-docs/carpeta/<int:folder_id>/pizarra/nueva/', views.my_docs_whiteboard_new, name='my_docs_whiteboard_new'),
    path('mis-docs/pizarra/<int:whiteboard_id>/', views.my_docs_whiteboard, name='my_docs_whiteboard'),
    path('mis-docs/pizarra/<int:whiteboard_id>/guardar/', views.my_docs_whiteboard_save, name='my_docs_whiteboard_save'),
    path('mis-docs/pizarra/<int:whiteboard_id>/eliminar/', views.my_docs_whiteboard_delete, name='my_docs_whiteboard_delete'),
    path('mis-docs/pizarra/<int:whiteboard_id>/compartir/', views.my_docs_whiteboard_share, name='my_docs_whiteboard_share'),
    # CAD
    path('mis-docs/carpeta/<int:folder_id>/cad/nuevo/', views.my_docs_cad_new, name='my_docs_cad_new'),
    path('mis-docs/cad/<int:cad_id>/', views.my_docs_cad, name='my_docs_cad'),
    path('mis-docs/cad/<int:cad_id>/guardar/', views.my_docs_cad_save, name='my_docs_cad_save'),
    path('mis-docs/cad/<int:cad_id>/eliminar/', views.my_docs_cad_delete, name='my_docs_cad_delete'),
    # Capturador de archivos
    path('mis-docs/carpeta/<int:folder_id>/capturador/', views.folder_capture_toggle, name='folder_capture_toggle'),
    path('captura/<uuid:token>/', views.folder_capture_view, name='folder_capture_view'),
    path('captura/<uuid:token>/subir/', views.folder_capture_upload, name='folder_capture_upload'),
    # Compartir carpeta directamente con usuario/empresa
    path('mis-docs/carpeta/<int:folder_id>/compartir-con/', views.folder_share_api,    name='folder_share_api'),
    path('mis-docs/carpeta/<int:folder_id>/compartir-con-todos/', views.folder_share_all, name='folder_share_all'),
    path('mis-docs/api/buscar-destinatarios/',              views.folder_share_search, name='folder_share_search'),
    path('mis-docs/compartida/<int:folder_id>/',            views.shared_folder_view,  name='shared_folder_view'),
    # Presentaciones
    path('mis-docs/carpeta/<int:folder_id>/presentacion/nueva/',     views.my_docs_presentation_new,     name='my_docs_presentation_new'),
    path('mis-docs/presentacion/<int:presentation_id>/',             views.my_docs_presentation_edit,    name='my_docs_presentation_edit'),
    path('mis-docs/presentacion/<int:presentation_id>/eliminar/',    views.my_docs_presentation_delete,  name='my_docs_presentation_delete'),
    path('mis-docs/presentacion/<int:presentation_id>/presentar/',   views.my_docs_presentation_present, name='my_docs_presentation_present'),
    path('mis-docs/presentacion/<int:presentation_id>/compartir/',   views.my_docs_presentation_share,   name='my_docs_presentation_share'),
    path('presentacion/<uuid:token>/',                               views.public_presentation_view,     name='public_presentation'),
    path('mis-docs/api/buscar/',                                     views.my_docs_search,               name='my_docs_search'),
    # Enlaces guardados
    path('mis-docs/enlaces/nuevo/',                    views.my_docs_link_create, name='my_docs_link_create'),
    path('mis-docs/enlaces/<int:link_id>/eliminar/',   views.my_docs_link_delete, name='my_docs_link_delete'),
    path('mis-docs/enlaces/<int:link_id>/toggle/',     views.my_docs_link_toggle, name='my_docs_link_toggle'),
    path('enlaces/',                                   views.saved_links,          name='saved_links'),
    path('nota/<uuid:token>/', views.public_note_view, name='public_note'),
    path('archivo/<uuid:token>/', views.public_file_view, name='public_file'),
    path('carpeta/<uuid:token>/', views.public_folder_view, name='public_folder'),
    path('pizarra/<uuid:token>/', views.public_whiteboard_view, name='public_whiteboard'),
    # Profesores
    path('profesores/', views.teachers_list, name='teachers'),
    path('profesores/<int:teacher_id>/', views.teacher_detail, name='teacher_detail'),
    path('profesores/<int:teacher_id>/mensaje/', views.teacher_send_message, name='teacher_send_message'),
    path('profesores/<int:teacher_id>/valorar/', views.teacher_rate, name='teacher_rate'),
    # Listas de chequeo
    path('checklists/',                                    views.checklists,              name='checklists'),
    path('checklists/nueva/',                              views.checklist_create,        name='checklist_create'),
    path('checklists/<int:pk>/',                           views.checklist_detail,        name='checklist_detail'),
    path('checklists/<int:pk>/eliminar/',                  views.checklist_delete,        name='checklist_delete'),
    path('checklists/<int:pk>/toggle-public/',             views.checklist_toggle_public, name='checklist_toggle_public'),
    path('checklists/<int:pk>/renombrar/',                 views.checklist_rename,        name='checklist_rename'),
    path('checklists/<int:pk>/item/add/',                  views.checklist_item_add,      name='checklist_item_add'),
    path('checklists/item/<int:item_id>/toggle/',          views.checklist_item_toggle,       name='checklist_item_toggle'),
    path('checklists/item/<int:item_id>/eliminar/',        views.checklist_item_delete,       name='checklist_item_delete'),
    path('checklists/item/<int:item_id>/duracion/',        views.checklist_item_set_duration, name='checklist_item_set_duration'),
    path('checklists/<int:pk>/reorder/',                   views.checklist_item_reorder,      name='checklist_item_reorder'),
    path('checklist/<uuid:token>/',                        views.public_checklist_view,       name='public_checklist'),
    # Bandeja del profesor
    path('mis-mensajes/', views.teacher_inbox, name='teacher_inbox'),
    path('mis-mensajes/<int:student_id>/', views.teacher_thread, name='teacher_thread'),
    path('cursos/', views.course_list, name='course_list'),
    path('cursos/<slug:slug>/', views.course_detail, name='course_detail'),
    path('cursos/<slug:slug>/inscribirse/', views.enroll, name='enroll'),
    path('cursos/<slug:slug>/clase/<int:lesson_id>/completar/', views.toggle_lesson, name='toggle_lesson'),
    path('cursos/<slug:slug>/tarea/<int:task_id>/entregar/', views.submit_task, name='submit_task'),
    path('cursos/<slug:slug>/clase/<int:lesson_id>/comentar/', views.add_comment, name='add_comment'),
    path('cursos/<slug:slug>/valorar/', views.review_course, name='review_course'),
    path('cursos/<slug:slug>/examen/', views.take_exam, name='take_exam'),
    path('cursos/<slug:slug>/examen/<int:attempt_id>/resultado/', views.exam_result, name='exam_result'),
    path('cursos/<slug:slug>/certificado/', views.certificate, name='certificate'),
]
